export const SOCIAL_PLATFORMS = [
  { value: 'no-icon', label: 'No Icon' },
  { value: 'apple-app-store', label: 'Apple App Store' },
  { value: 'artstation', label: 'ArtStation' },
  { value: 'behance', label: 'Behance' },
  { value: 'discord', label: 'Discord' },
  { value: 'etsy', label: 'Etsy' },
  { value: 'facebook', label: 'Facebook' },
  { value: 'github', label: 'GitHub' },
  { value: 'google-play-store', label: 'Google Play Store' },
  { value: 'instagram', label: 'Instagram' },
  { value: 'linkedin', label: 'LinkedIn' },
  { value: 'medium', label: 'Medium' },
  { value: 'patreon', label: 'Patreon' },
  { value: 'pinterest', label: 'Pinterest' },
  { value: 'reddit', label: 'Reddit' },
  { value: 'snapchat', label: 'Snapchat' },
  { value: 'soundcloud', label: 'SoundCloud' },
  { value: 'spotify', label: 'Spotify' },
  { value: 'tiktok', label: 'TikTok' },
  { value: 'telegram', label: 'Telegram' },
  { value: 'tumblr', label: 'Tumblr' },
  { value: 'twitch', label: 'Twitch' },
  { value: 'twitter', label: 'Twitter' },
  { value: 'vimeo', label: 'Vimeo' },
  { value: 'weibo', label: 'Weibo' },
  { value: 'whatsapp', label: 'WhatsApp' },
  { value: 'x', label: 'X' },
  { value: 'youtube', label: 'YouTube' },
];

export const FONTS = [
  'Inter',
  'Montserrat',
  'Quicksand',
  'Prompt',
  'Outfit',
  'Antonio',
  'IBM Plex Mono',
  'Space Mono',
  'EB Garamond',
  'Source Serif Pro',
];
